Repository cleaner00/PLEA-STREET, pull requests merged in 2021-11, with the labels that each got.

#29 [#23] [#28] Feat: marker click event & Hotfix: 지도 검색 page
  public/img/markerImage/recycleMarker.png
  public/img/markerImage/trashMarker.png
  src/page/ShowPage.js
Labels: bug, additional dev

#31 [#21][#22][#30]feat: 로그인, 게시판 커뮤니티페이지 구현완료
  src/App.js
  src/component/PostListComponent.js
  src/page/CommunityPage.js
  src/page/PostWrite.js
  src/page/PostedPage.js
  src/page/ShowPage.js
Labels: additional dev

#35 [#34] Bug: 마커를 바로 눌러서 나오는 길찾기 버튼 오류 해결
  src/page/ShowPage.js
Labels: bug

#38 [#37] 구 검색 위치 이상한 문제 해결
  src/page/ShowPage.js
Labels: bug

#43 [#40][#42] Feat: 추가 퀴즈결과 페이지, 카톡 공유버튼
  package.json
  public/img/resultImage/adult.jpg
  public/img/resultImage/baby.jpg
  public/img/resultImage/hero.jpg
  public/img/resultImage/student.jpg
  public/index.html
  src/App.js
  src/component/KakaoShare.js
  src/component/TestOptions.js
  src/component/TestResult.js
  src/util/question.json
  src/util/result.json
  yarn.lock
Labels: additional dev

#53 [#24] Design: 지도 마커 infowindow변경, CSS 변경
  src/page/ShowPage.js
Labels: additional dev

#67 [#41][#64][#65][#66] Design: 추가 OX퀴즈 CSS
  public/img/markerImage/trashMarker3.png
  public/img/questionImage/bubbleWrap.jpg
  public/img/questionImage/can.jpg
  public/img/questionImage/chickenBone.jpg
  public/img/questionImage/egg.jpg
  public/img/questionImage/foodTrash.jpg
  public/img/questionImage/icepack.jpeg
  public/img/questionImage/o.png
  public/img/questionImage/receipt.jpg
  public/img/questionImage/rice.jpeg
  public/img/questionImage/searching.png
  public/img/questionImage/silCase.jpg
  public/img/questionImage/x.png
  public/img/questionImage/yeopgi.jpeg
  public/img/resultImage/adult.jpg
  public/img/resultImage/adult.png
  public/img/resultImage/baby.jpg
  public/img/resultImage/baby.png
  public/img/resultImage/click.png
  public/img/resultImage/graduate.png
  public/img/resultImage/hero.jpg
  public/img/resultImage/hero.png
  public/img/resultImage/kakao.png
  public/img/resultImage/link.png
  public/img/resultImage/reset.png
  public/img/resultImage/student.jpg
  public/img/resultImage/student.png
  src/App.css
  src/component/KakaoShare.js
  src/component/TestOptions.js
  src/component/TestResult.js
  src/component/TestResultDetail.js
  src/component/TestStartPage.js
  src/styles/fonts/SDSamliphopangcheOutline.otf
  src/util/question.json
  src/util/result.json
Labels: additional dev

#73 [#71]Design: 추가 CSS 애니메이션 효과
  src/component/TestOptions.js
  src/component/TestResult.js
Labels: additional dev
